### ISSUE TITLE
Remove close button

### ISSUE THREAD

**Issue by artemanufrij** [kmal-kenneth/monilet#10]
Hey @kmal-kenneth I think it would be more beutiful if you remove close button from applet.

**Comment by kmalkenneth** [comment]
To be honest I do not know How to remove the close button.
I would like to improve the applet, but I don't know how to achieve this. the truth is that i'm a newbie and this is my first application.
I did it to learn, and it was very difficult for me. I am a new student in software engineering.
But I am willing to learn and accept advice and help.

**Comment by kmalkenneth** [comment]
I know I can eliminate it if I do it completely in libcairo.

**Comment by artemanufrij** [comment]
https://valadoc.org/gtk+-3.0/Gtk.Window.set_titlebar.html

**Comment by artemanufrij** [comment]
Try with null or just empty Headerbar
https://valadoc.org/gtk+-3.0/Gtk.HeaderBar.html
`show_close_button = false`

**Comment by kmalkenneth** [comment]
I will study your suggestions and do some experiments. if I get acceptable results, I will launch another version. Thanks for the support.

**Comment by artemanufrij** [comment]
@kmal-kenneth you are welcome :)
